services:
  tweakio:
    image: varthe/tweakio:latest
    container_name: tweakio
    restart: unless-stopped
    ports:
      - 3185:3185
    user: $PUID:$PGID
    env_file:
      - .env
    profiles:
      - all
      - tweakio
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
