services:
  aiomanager:
    image: ghcr.io/sonicx161/aiomanager:latest
    container_name: aiomanager
    restart: unless-stopped
    expose:
      - ${PORT:-1610}
    env_file:
      - .env
    volumes:
      - ${DOCKER_DATA_DIR}/aiomanager/data:/app/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    labels:
      - traefik.enable=true
      - traefik.http.routers.aiomanager.rule=Host(`${AIOMANAGER_HOSTNAME?}`)
      - traefik.http.routers.aiomanager.entrypoints=websecure
      - traefik.http.routers.aiomanager.tls.certresolver=letsencrypt
      - traefik.http.routers.aiomanager.middlewares=authelia@docker
      - traefik.http.services.aiomanager.loadbalancer.server.port=${PORT:-1610}
    #depends_on: # un-comment if using postgres
    #  aiomanager_postgres:
    #    condition: service_healthy
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "server/healthcheck.js"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 20s
    profiles:
      - aiomanager
      - all

  #aiomanager_postgres: # un-comment if using postgres
  #  image: postgres:18-alpine
  #  container_name: aiomanager_postgres
  #  restart: unless-stopped
  #  environment:
  #    - POSTGRES_USER=aiomanager
  #    - POSTGRES_PASSWORD=aiomanager
  #    - POSTGRES_DB=aiomanager
  #  volumes:
  #    - ${DOCKER_DATA_DIR}/aiomanager/postgres:/var/lib/postgresql/data
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U aiomanager -d aiomanager"]
  #    start_period: 1m
  #    interval: 20s
  #    timeout: 5s
  #    retries: 5
  #  profiles:
  #    - aiomanager
  #    - all
